ys = ys or {}

local var0_0 = {}

ys.Battle.BattleCardPuzzleEvent = var0_0
var0_0.CARD_PUZZLE_INIT = "CARD_PUZZLE_INIT"
var0_0.UPDATE_COMMON_HP = "UPDATE_COMMON_HP"
var0_0.UPDATE_FLEET_SHIP = "UPDATE_FLEET_SHIP"
var0_0.UPDATE_FLEET_BUFFS = "UPDATE_FLEET_BUFFS"
var0_0.UPDATE_CARDS = "UPDATE_CARDS"
var0_0.BOARD_CLICK_REQUEST = "BOARD_CLICK_REQUEST"
var0_0.COMMON_BUTTON_ENABLE = "COMMON_BUTTON_ENABLE"
var0_0.LONG_PRESS_BULLET_TIME = "LONG_PRESS_BULLET_TIME"
var0_0.ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK"
var0_0.UPDATE_FLEET_ATTR = "UPDATE_FLEET_ATTR"
var0_0.ON_BOARD_CLICK = "ON_BOARD_CLICK"
var0_0.FLEET_MOVE_TO = "FLEET_MOVE_TO"
var0_0.UPDATE_CARD_TARGET_FILTER = "UPDATE_CARD_TARGET_FILTER"
var0_0.SHOW_CARD_DETAIL = "SHOW_CARD_DETAIL"
