ys = ys or {}

local var0 = {}

ys.Battle.BattleCardPuzzleEvent = var0
var0.CARD_PUZZLE_INIT = "CARD_PUZZLE_INIT"
var0.UPDATE_COMMON_HP = "UPDATE_COMMON_HP"
var0.UPDATE_FLEET_SHIP = "UPDATE_FLEET_SHIP"
var0.UPDATE_FLEET_BUFFS = "UPDATE_FLEET_BUFFS"
var0.UPDATE_CARDS = "UPDATE_CARDS"
var0.BOARD_CLICK_REQUEST = "BOARD_CLICK_REQUEST"
var0.COMMON_BUTTON_ENABLE = "COMMON_BUTTON_ENABLE"
var0.LONG_PRESS_BULLET_TIME = "LONG_PRESS_BULLET_TIME"
var0.ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK"
var0.UPDATE_FLEET_ATTR = "UPDATE_FLEET_ATTR"
var0.ON_BOARD_CLICK = "ON_BOARD_CLICK"
var0.FLEET_MOVE_TO = "FLEET_MOVE_TO"
var0.UPDATE_CARD_TARGET_FILTER = "UPDATE_CARD_TARGET_FILTER"
var0.SHOW_CARD_DETAIL = "SHOW_CARD_DETAIL"
