pg = pg or {}
pg.child2_shop = {
	{
		goods_type = 1,
		name = "Fitness +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2022,
		desc = "Gain a fixed +10 Fitness",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 1,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2023,
		desc = "Gain a fixed +10 Knowledge",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 2,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2024,
		desc = "Gain a fixed +10 Dexterity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2025,
		desc = "Gain a fixed +10 Sensitivity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 4,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +2",
		resource_num = 8,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2026,
		desc = "Gain a fixed +2 Mood",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 5,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2027,
		desc = "Gain a fixed +20 Fitness",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 6,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2028,
		desc = "Gain a fixed +20 Knowledge",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 7,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2029,
		desc = "Gain a fixed +20 Dexterity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 8,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2030,
		desc = "Gain a fixed +20 Sensitivity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +4",
		resource_num = 12,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2031,
		desc = "Gain a fixed +4 Mood",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 10,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness +40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2032,
		desc = "Gain a fixed +40 Fitness",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 11,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2033,
		desc = "Gain a fixed +40 Knowledge",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 12,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2034,
		desc = "Gain a fixed +40 Dexterity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 13,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2035,
		desc = "Gain a fixed +40 Sensitivity",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 14,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +6",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2036,
		desc = "Gain a fixed +6 Mood",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 15,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2001,
		desc = "Activity Fitness Boost (3 Turns)",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 16,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "Knowledge Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2002,
		desc = "Activity Knowledge Boost (3 Turns)",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 17,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "Dexterity Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2003,
		desc = "Activity Dexterity Boost (3 Turns)",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 18,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "Sensitivity Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2004,
		desc = "Activity Sensitivity Boost (3 Turns)",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 19,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "Lucky Coupon",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2005,
		desc = "Grants between 20 and 100 Funds when obtained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 20,
		icon = "buff_2005"
	},
	{
		goods_type = 1,
		name = "Random Fitness Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2006,
		desc = "For 3 turns, when you complete an activity, you gain a little Fitness.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 21,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "Random Knowledge Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2007,
		desc = "For 3 turns, when you complete an activity, you gain a little Knowledge.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 22,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "Random Dexterity Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2008,
		desc = "For 3 turns, when you complete an activity, you gain a little Dexterity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 23,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "Random Sensitivity Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2009,
		desc = "For 3 turns, when you complete an activity, you gain a little Sensitivity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 24,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "Random Fitness Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2010,
		desc = "For 3 turns, when you complete an activity, you gain some Fitness.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 25,
		icon = "benefit_2_tineng_2"
	},
	{
		goods_type = 1,
		name = "Random Knowledge Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2011,
		desc = "For 3 turns, when you complete an activity, you gain some Knowledge.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 26,
		icon = "benefit_2_zhishi_2"
	},
	{
		goods_type = 1,
		name = "Random Dexterity Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2012,
		desc = "For 3 turns, when you complete an activity, you gain some Dexterity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 27,
		icon = "benefit_2_shijian_2"
	},
	{
		goods_type = 1,
		name = "Random Sensitivity Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2013,
		desc = "For 3 turns, when you complete an activity, you gain some Sensitivity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 28,
		icon = "benefit_2_ganzhi_2"
	},
	{
		goods_type = 1,
		name = "Delayed Random Fitness Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2014,
		desc = "When the next turn ends, you gain a lot of Fitness.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 29,
		icon = "benefit_2_tineng_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Knowledge Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2015,
		desc = "When the next turn ends, you gain a lot of Knowledge.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 30,
		icon = "benefit_2_zhishi_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Dexterity Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2016,
		desc = "When the next turn ends, you gain a lot of Dexterity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 31,
		icon = "benefit_2_shijian_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Sensitivity Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2017,
		desc = "When the next turn ends, you gain a lot of Sensitivity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 32,
		icon = "benefit_2_ganzhi_3"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery",
		resource_num = 25,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2018,
		desc = "For 3 turns, when the turn starts, you recover a little Mood.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 33,
		icon = "benefit_2_xinqing_1"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery+",
		resource_num = 36,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2019,
		desc = "For 3 turns, when the turn starts, you recover some Mood.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 34,
		icon = "benefit_2_xinqing_2"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery++",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2020,
		desc = "For 3 turns, when the turn starts, you recover a lot of Mood.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 35,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 1,
		name = "Permanent Random Mood Recovery",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2021,
		desc = "When the turn starts, you recover some Mood.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 36,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 3,
		name = "Action Point Recovery",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "Purchase to recover 1 action point.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 37,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 3,
		name = "Action Point Recovery+",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "Purchase to recover 2 action points.",
		goods_id_list = "",
		goods_num = 2,
		resource_type = 1,
		id = 38,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 1,
		name = "Fitness Conversion - Knowledge",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2037,
		desc = "For 3 turns, activities give more Fitness and less Knowledge.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 39,
		icon = "benefit_2_tinengzhishiz"
	},
	{
		goods_type = 1,
		name = "Knowledge Conversion - Fitness",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2038,
		desc = "For 3 turns, activities give more Knowledge and less Fitness.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 40,
		icon = "benefit_2_zhishitinengz"
	},
	{
		goods_type = 1,
		name = "Dexterity Conversion - Sensitivity",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2039,
		desc = "For 3 turns, activities give more Dexterity and less Sensitivity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 41,
		icon = "benefit_2_shijianganzhiz"
	},
	{
		goods_type = 1,
		name = "Sensitivity Conversion - Dexterity",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2040,
		desc = "For 3 turns, activities give more Sensitivity and less Dexterity.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 42,
		icon = "benefit_2_ganzhishijianz"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2041,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 43,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2043,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 44,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2045,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 45,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2047,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 46,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2049,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 47,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2051,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 48,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2053,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 49,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2055,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 50,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2057,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 51,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2059,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 52,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2061,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 53,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2063,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 54,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2089,
		desc = "Slightly increases stats gained from the 1st activity slot.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 55,
		icon = "benefit_2_xingcheng1_1"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2090,
		desc = "Moderately increases stats gained from the 1st activity slot.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 56,
		icon = "benefit_2_xingcheng1_2"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2091,
		desc = "Greatly increases stats gained from the 1st activity slot.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 57,
		icon = "benefit_2_xingcheng1_3"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2092,
		desc = "Slightly increases stats gained from odd-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 58,
		icon = "benefit_2_xingchengji_1"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2093,
		desc = "Moderately increases stats gained from odd-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 59,
		icon = "benefit_2_xingchengji_2"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2094,
		desc = "Greatly increases stats gained from odd-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 60,
		icon = "benefit_2_xingchengji_3"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2095,
		desc = "Slightly increases stats gained from even-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 61,
		icon = "benefit_2_xingchengou_1"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2096,
		desc = "Moderately increases stats gained from even-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 62,
		icon = "benefit_2_xingchengou_2"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2097,
		desc = "Greatly increases stats gained from even-numbered activity slots.",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 63,
		icon = "benefit_2_xingchengou_3"
	},
	[3001] = {
		goods_type = 2,
		name = "Fitness +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 301,
		desc = "Gain a fixed +10 Fitness",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 3001,
		icon = "attr_tineng2"
	},
	[3002] = {
		goods_type = 2,
		name = "Knowledge +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +10 Knowledge",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 3002,
		icon = "attr_zhishi2"
	},
	[3003] = {
		goods_type = 2,
		name = "Dexterity +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +10 Dexterity",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 3003,
		icon = "attr_shijian2"
	},
	[3004] = {
		goods_type = 2,
		name = "Sensitivity +10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 304,
		desc = "Gain a fixed +10 Sensitivity",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 3004,
		icon = "attr_ganzhi2"
	},
	[3005] = {
		goods_type = 2,
		name = "Fitness +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 301,
		desc = "Gain a fixed +20 Fitness",
		goods_id_list = "",
		goods_num = 20,
		resource_type = 1,
		id = 3005,
		icon = "attr_tineng2"
	},
	[3006] = {
		goods_type = 2,
		name = "Knowledge +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +20 Knowledge",
		goods_id_list = "",
		goods_num = 20,
		resource_type = 1,
		id = 3006,
		icon = "attr_zhishi2"
	},
	[3007] = {
		goods_type = 2,
		name = "Dexterity +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +20 Dexterity",
		goods_id_list = "",
		goods_num = 20,
		resource_type = 1,
		id = 3007,
		icon = "attr_shijian2"
	},
	[3008] = {
		goods_type = 2,
		name = "Sensitivity +20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 304,
		desc = "Gain a fixed +20 Sensitivity",
		goods_id_list = "",
		goods_num = 20,
		resource_type = 1,
		id = 3008,
		icon = "attr_ganzhi2"
	},
	[3009] = {
		goods_type = 2,
		name = "Fitness +40",
		resource_num = 60,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 301,
		desc = "Gain a fixed +40 Fitness",
		goods_id_list = "",
		goods_num = 40,
		resource_type = 1,
		id = 3009,
		icon = "attr_tineng2"
	},
	[3010] = {
		goods_type = 2,
		name = "Knowledge +40",
		resource_num = 60,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +40 Knowledge",
		goods_id_list = "",
		goods_num = 40,
		resource_type = 1,
		id = 3010,
		icon = "attr_zhishi2"
	},
	[3011] = {
		goods_type = 2,
		name = "Dexterity +40",
		resource_num = 60,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +40 Dexterity",
		goods_id_list = "",
		goods_num = 40,
		resource_type = 1,
		id = 3011,
		icon = "attr_shijian2"
	},
	[3012] = {
		goods_type = 2,
		name = "Sensitivity +40",
		resource_num = 60,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 304,
		desc = "Gain a fixed +40 Sensitivity",
		goods_id_list = "",
		goods_num = 40,
		resource_type = 1,
		id = 3012,
		icon = "attr_ganzhi2"
	},
	[3013] = {
		goods_type = 2,
		name = "Fitness +60",
		resource_num = 90,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 301,
		desc = "Gain a fixed +60 Fitness",
		goods_id_list = "",
		goods_num = 60,
		resource_type = 1,
		id = 3013,
		icon = "attr_tineng2"
	},
	[3014] = {
		goods_type = 2,
		name = "Knowledge +60",
		resource_num = 90,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +60 Knowledge",
		goods_id_list = "",
		goods_num = 60,
		resource_type = 1,
		id = 3014,
		icon = "attr_zhishi2"
	},
	[3015] = {
		goods_type = 2,
		name = "Dexterity +60",
		resource_num = 90,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +60 Dexterity",
		goods_id_list = "",
		goods_num = 60,
		resource_type = 1,
		id = 3015,
		icon = "attr_shijian2"
	},
	[3016] = {
		goods_type = 2,
		name = "Sensitivity +60",
		resource_num = 90,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 304,
		desc = "Gain a fixed +60 Sensitivity",
		goods_id_list = "",
		goods_num = 60,
		resource_type = 1,
		id = 3016,
		icon = "attr_ganzhi2"
	},
	[3017] = {
		goods_type = 2,
		name = "Fitness +80",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 301,
		desc = "Gain a fixed +80 Fitness",
		goods_id_list = "",
		goods_num = 80,
		resource_type = 1,
		id = 3017,
		icon = "attr_tineng2"
	},
	[3018] = {
		goods_type = 2,
		name = "Knowledge +80",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +80 Knowledge",
		goods_id_list = "",
		goods_num = 80,
		resource_type = 1,
		id = 3018,
		icon = "attr_zhishi2"
	},
	[3019] = {
		goods_type = 2,
		name = "Dexterity +80",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +80 Dexterity",
		goods_id_list = "",
		goods_num = 80,
		resource_type = 1,
		id = 3019,
		icon = "attr_shijian2"
	},
	[3020] = {
		goods_type = 2,
		name = "Sensitivity +80",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 304,
		desc = "Gain a fixed +80 Sensitivity",
		goods_id_list = "",
		goods_num = 80,
		resource_type = 1,
		id = 3020,
		icon = "attr_ganzhi2"
	},
	[3101] = {
		goods_type = 3,
		name = "Mood +2",
		resource_num = 8,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +2 Mood",
		goods_id_list = "",
		goods_num = 2,
		resource_type = 1,
		id = 3101,
		icon = "res_xinqing2"
	},
	[3102] = {
		goods_type = 3,
		name = "Mood +4",
		resource_num = 12,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +4 Mood",
		goods_id_list = "",
		goods_num = 4,
		resource_type = 1,
		id = 3102,
		icon = "res_xinqing2"
	},
	[3103] = {
		goods_type = 3,
		name = "Mood +6",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +6 Mood",
		goods_id_list = "",
		goods_num = 6,
		resource_type = 1,
		id = 3103,
		icon = "res_xinqing2"
	},
	[3104] = {
		goods_type = 3,
		name = "Mood +8",
		resource_num = 20,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +8 Mood",
		goods_id_list = "",
		goods_num = 8,
		resource_type = 1,
		id = 3104,
		icon = "res_xinqing2"
	},
	[3105] = {
		goods_type = 3,
		name = "Mood +10",
		resource_num = 25,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 302,
		desc = "Gain a fixed +10 Mood",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 3105,
		icon = "res_xinqing2"
	},
	[3106] = {
		goods_type = 3,
		name = "AP +1",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 303,
		desc = "Gain a fixed +1 AP",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3106,
		icon = "res_xingdongli2"
	},
	[3107] = {
		goods_type = 3,
		name = "Gain a fixed +1 Fortune Teller refreshes",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 305,
		desc = "Gain a fixed +1 Fortune Teller refreshes",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3107,
		icon = "res_refresh1"
	},
	[3108] = {
		goods_type = 3,
		name = "Tarot Redraws +1",
		resource_num = 100,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 306,
		desc = "Gain a fixed +1 Tarot Card/Reading redraw",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3108,
		icon = "res_refresh2"
	},
	[3109] = {
		goods_type = 5,
		name = "Level Up Reading",
		resource_num = 100,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 1,
		desc = "Select a Reading to level up",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3109,
		icon = "buff_2005"
	},
	[3110] = {
		goods_type = 5,
		name = "Level Up Reading",
		resource_num = 100,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 1,
		desc = "Select a Reading to level up",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3110,
		icon = "buff_2005"
	},
	[3111] = {
		goods_type = 5,
		name = "Level Up Reading",
		resource_num = 100,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 1,
		desc = "Select a Reading to level up",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 3111,
		icon = "buff_2005"
	},
	[3112] = {
		goods_type = 4,
		name = "Temperance Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Temperance Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3112,
		icon = "buff_entry_14",
		goods_id_list = {
			3830008
		}
	},
	[3116] = {
		goods_type = 4,
		name = "The Sun Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Sun Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3116,
		icon = "buff_entry_19",
		goods_id_list = {
			3830009
		}
	},
	[3120] = {
		goods_type = 4,
		name = "The Star Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Star Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3120,
		icon = "buff_entry_17",
		goods_id_list = {
			3830010
		}
	},
	[3124] = {
		goods_type = 4,
		name = "The Tower Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Tower Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3124,
		icon = "buff_entry_16",
		goods_id_list = {
			3830011
		}
	},
	[3128] = {
		goods_type = 4,
		name = "The Devil Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Devil Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3128,
		icon = "buff_entry_15",
		goods_id_list = {
			3830012
		}
	},
	[3132] = {
		goods_type = 4,
		name = "The Empress Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Empress Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3132,
		icon = "buff_entry_3",
		goods_id_list = {
			3830013
		}
	},
	[3136] = {
		goods_type = 4,
		name = "The Hanged Man Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Hanged Man Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3136,
		icon = "buff_entry_12",
		goods_id_list = {
			3830014
		}
	},
	[3140] = {
		goods_type = 4,
		name = "The World Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The World Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3140,
		icon = "buff_entry_21",
		goods_id_list = {
			3830015
		}
	},
	[3144] = {
		goods_type = 4,
		name = "The Moon Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Moon Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3144,
		icon = "buff_entry_18",
		goods_id_list = {
			3830016
		}
	},
	[3148] = {
		goods_type = 4,
		name = "The Chariot Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Chariot Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3148,
		icon = "buff_entry_7",
		goods_id_list = {
			3830017
		}
	},
	[3152] = {
		goods_type = 4,
		name = "Judgment Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Judgment Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3152,
		icon = "buff_entry_20",
		goods_id_list = {
			3830018
		}
	},
	[3156] = {
		goods_type = 4,
		name = "Justice Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Justice Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3156,
		icon = "buff_entry_11",
		goods_id_list = {
			3830019
		}
	},
	[3160] = {
		goods_type = 4,
		name = "The High Priestess Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The High Priestess Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3160,
		icon = "buff_entry_2",
		goods_id_list = {
			3830020
		}
	},
	[3164] = {
		goods_type = 4,
		name = "Wheel of Fortune Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Wheel of Fortune Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3164,
		icon = "buff_entry_10",
		goods_id_list = {
			3830021
		}
	},
	[3168] = {
		goods_type = 4,
		name = "Strength Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Strength Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3168,
		icon = "buff_entry_8",
		goods_id_list = {
			3830022
		}
	},
	[3172] = {
		goods_type = 4,
		name = "The Magician Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Magician Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3172,
		icon = "buff_entry_1",
		goods_id_list = {
			3830023
		}
	},
	[3176] = {
		goods_type = 4,
		name = "The Hierophant Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Hierophant Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3176,
		icon = "buff_entry_5",
		goods_id_list = {
			3830024
		}
	},
	[3180] = {
		goods_type = 4,
		name = "The Fool Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Fool Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3180,
		icon = "buff_entry_0",
		goods_id_list = {
			3830025
		}
	},
	[3184] = {
		goods_type = 4,
		name = "Death Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Death Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3184,
		icon = "buff_entry_13",
		goods_id_list = {
			3830026
		}
	},
	[3188] = {
		goods_type = 4,
		name = "The Emperor Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Emperor Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3188,
		icon = "buff_entry_4",
		goods_id_list = {
			3830027
		}
	},
	[3192] = {
		goods_type = 4,
		name = "The Hermit Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Hermit Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3192,
		icon = "buff_entry_9",
		goods_id_list = {
			3830028
		}
	},
	[3196] = {
		goods_type = 4,
		name = "The Lovers Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 The Lovers Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3196,
		icon = "buff_entry_6",
		goods_id_list = {
			3830029
		}
	},
	[3200] = {
		goods_type = 4,
		name = "Swords Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Swords Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3200,
		icon = "buff_entry_22",
		goods_id_list = {
			3830030
		}
	},
	[3204] = {
		goods_type = 4,
		name = "Wands Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Wands Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3204,
		icon = "buff_entry_24",
		goods_id_list = {
			3830031
		}
	},
	[3208] = {
		goods_type = 4,
		name = "Cups Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Cups Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3208,
		icon = "buff_entry_23",
		goods_id_list = {
			3830032
		}
	},
	[3212] = {
		goods_type = 4,
		name = "Pentacles Reading",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 Pentacles Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3212,
		icon = "buff_entry_25",
		goods_id_list = {
			3830033
		}
	},
	[3216] = {
		goods_type = 4,
		name = "Random Temperance Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Temperance Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3216,
		icon = "buff_entry_14",
		goods_id_list = {
			3830034
		}
	},
	[3220] = {
		goods_type = 4,
		name = "Random The Sun Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Sun Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3220,
		icon = "buff_entry_19",
		goods_id_list = {
			3830035
		}
	},
	[3224] = {
		goods_type = 4,
		name = "Random The Star Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Star Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3224,
		icon = "buff_entry_17",
		goods_id_list = {
			3830036
		}
	},
	[3228] = {
		goods_type = 4,
		name = "Random The Tower Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Tower Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3228,
		icon = "buff_entry_16",
		goods_id_list = {
			3830037
		}
	},
	[3232] = {
		goods_type = 4,
		name = "Random The Devil Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Devil Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3232,
		icon = "buff_entry_15",
		goods_id_list = {
			3830038
		}
	},
	[3236] = {
		goods_type = 4,
		name = "Random The Empress Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Empress Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3236,
		icon = "buff_entry_3",
		goods_id_list = {
			3830039
		}
	},
	[3240] = {
		goods_type = 4,
		name = "Random The Hanged Man Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Hanged Man Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3240,
		icon = "buff_entry_12",
		goods_id_list = {
			3830040
		}
	},
	[3244] = {
		goods_type = 4,
		name = "Random The World Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The World Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3244,
		icon = "buff_entry_21",
		goods_id_list = {
			3830041
		}
	},
	[3248] = {
		goods_type = 4,
		name = "Random The Moon Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Moon Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3248,
		icon = "buff_entry_18",
		goods_id_list = {
			3830042
		}
	},
	[3252] = {
		goods_type = 4,
		name = "Random The Chariot Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Chariot Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3252,
		icon = "buff_entry_7",
		goods_id_list = {
			3830043
		}
	},
	[3256] = {
		goods_type = 4,
		name = "Random Judgment Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Judgment Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3256,
		icon = "buff_entry_20",
		goods_id_list = {
			3830044
		}
	},
	[3260] = {
		goods_type = 4,
		name = "Random Justice Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Justice Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3260,
		icon = "buff_entry_11",
		goods_id_list = {
			3830045
		}
	},
	[3264] = {
		goods_type = 4,
		name = "Random The High Priestess Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The High Priestess Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3264,
		icon = "buff_entry_2",
		goods_id_list = {
			3830046
		}
	},
	[3268] = {
		goods_type = 4,
		name = "Random Wheel of Fortune Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Wheel of Fortune Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3268,
		icon = "buff_entry_10",
		goods_id_list = {
			3830047
		}
	},
	[3272] = {
		goods_type = 4,
		name = "Random Strength Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Strength Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3272,
		icon = "buff_entry_8",
		goods_id_list = {
			3830048
		}
	},
	[3276] = {
		goods_type = 4,
		name = "Random The Magician Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Magician Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3276,
		icon = "buff_entry_1",
		goods_id_list = {
			3830049
		}
	},
	[3280] = {
		goods_type = 4,
		name = "Random The Hierophant Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Hierophant Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3280,
		icon = "buff_entry_5",
		goods_id_list = {
			3830050
		}
	},
	[3284] = {
		goods_type = 4,
		name = "Random The Fool Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Fool Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3284,
		icon = "buff_entry_0",
		goods_id_list = {
			3830051
		}
	},
	[3288] = {
		goods_type = 4,
		name = "Random Death Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Death Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3288,
		icon = "buff_entry_13",
		goods_id_list = {
			3830052
		}
	},
	[3292] = {
		goods_type = 4,
		name = "Random The Emperor Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Emperor Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3292,
		icon = "buff_entry_4",
		goods_id_list = {
			3830053
		}
	},
	[3296] = {
		goods_type = 4,
		name = "Random The Hermit Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Hermit Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3296,
		icon = "buff_entry_9",
		goods_id_list = {
			3830054
		}
	},
	[3300] = {
		goods_type = 4,
		name = "Random The Lovers Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random The Lovers Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3300,
		icon = "buff_entry_6",
		goods_id_list = {
			3830055
		}
	},
	[3304] = {
		goods_type = 4,
		name = "Random Swords Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Swords Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3304,
		icon = "buff_entry_22",
		goods_id_list = {
			3830056
		}
	},
	[3308] = {
		goods_type = 4,
		name = "Random Wands Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Wands Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3308,
		icon = "buff_entry_24",
		goods_id_list = {
			3830057
		}
	},
	[3312] = {
		goods_type = 4,
		name = "Random Cups Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Cups Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3312,
		icon = "buff_entry_23",
		goods_id_list = {
			3830058
		}
	},
	[3316] = {
		goods_type = 4,
		name = "Random Pentacles Reading",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select and gain 1 random Pentacles Reading",
		goods_num = 1,
		resource_type = 1,
		id = 3316,
		icon = "buff_entry_25",
		goods_id_list = {
			3830059
		}
	},
	[3320] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 0,
		desc = "Select a Tarot Card",
		goods_num = 1,
		resource_type = 1,
		id = 3320,
		icon = "buff_2008",
		goods_id_list = {
			1000
		}
	},
	[9001] = {
		goods_type = 2,
		name = "300体能",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 301,
		desc = "[测试配置，无需本地化]300体能",
		goods_id_list = "",
		goods_num = 300,
		resource_type = 1,
		id = 9001,
		icon = "benefit_2_xingchengou_3"
	},
	[9002] = {
		goods_type = 2,
		name = "300知识",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 302,
		desc = "[测试配置，无需本地化]300知识",
		goods_id_list = "",
		goods_num = 300,
		resource_type = 1,
		id = 9002,
		icon = "benefit_2_xingchengou_3"
	},
	[9003] = {
		goods_type = 2,
		name = "300实践",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 303,
		desc = "[测试配置，无需本地化]300实践",
		goods_id_list = "",
		goods_num = 300,
		resource_type = 1,
		id = 9003,
		icon = "benefit_2_xingchengou_3"
	},
	[9004] = {
		goods_type = 2,
		name = "300感知",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 304,
		desc = "[测试配置，无需本地化]300感知",
		goods_id_list = "",
		goods_num = 300,
		resource_type = 1,
		id = 9004,
		icon = "benefit_2_xingchengou_3"
	},
	[9005] = {
		goods_type = 3,
		name = "300金钱",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 301,
		desc = "[测试配置，无需本地化]300金钱",
		goods_id_list = "",
		goods_num = 300,
		resource_type = 1,
		id = 9005,
		icon = "benefit_2_xingchengou_3"
	},
	[9006] = {
		goods_type = 3,
		name = "100心情",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 302,
		desc = "[测试配置，无需本地化]100心情",
		goods_id_list = "",
		goods_num = 100,
		resource_type = 1,
		id = 9006,
		icon = "benefit_2_xingchengou_3"
	},
	[9007] = {
		goods_type = 3,
		name = "3行动力",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 303,
		desc = "[测试配置，无需本地化]3行动力",
		goods_id_list = "",
		goods_num = 3,
		resource_type = 1,
		id = 9007,
		icon = "benefit_2_xingchengou_3"
	},
	[9008] = {
		goods_type = 3,
		name = "10好感度",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 304,
		desc = "[测试配置，无需本地化]10好感度",
		goods_id_list = "",
		goods_num = 10,
		resource_type = 1,
		id = 9008,
		icon = "benefit_2_xingchengou_3"
	},
	[9009] = {
		goods_type = 3,
		name = "5商店刷新次数",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 305,
		desc = "[测试配置，无需本地化]5商店刷新次数",
		goods_id_list = "",
		goods_num = 5,
		resource_type = 1,
		id = 9009,
		icon = "benefit_2_xingchengou_3"
	},
	[9010] = {
		goods_type = 3,
		name = "5塔罗牌和词条的刷新次数",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 306,
		desc = "[测试配置，无需本地化]5塔罗牌和词条的刷新次数",
		goods_id_list = "",
		goods_num = 5,
		resource_type = 1,
		id = 9010,
		icon = "benefit_2_xingchengou_3"
	},
	[9011] = {
		goods_type = 5,
		name = "升级次数",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 1,
		desc = "[测试配置，无需本地化]3选1",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9011,
		icon = "benefit_2_xingchengou_3"
	},
	[9012] = {
		goods_type = 2,
		name = "外向性格",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 305,
		desc = "[测试配置，无需本地化]3选1*2",
		goods_id_list = "",
		goods_num = 50,
		resource_type = 1,
		id = 9012,
		icon = "benefit_2_xingchengou_3"
	},
	[9013] = {
		goods_type = 2,
		name = "内向性格",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 305,
		desc = "[测试配置，无需本地化]3选1&2选1",
		goods_id_list = "",
		goods_num = -50,
		resource_type = 1,
		id = 9013,
		icon = "benefit_2_xingchengou_3"
	},
	[9014] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]1张塔罗牌",
		goods_num = 1,
		resource_type = 1,
		id = 9014,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9015] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 100,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]1张塔罗牌",
		goods_num = 1,
		resource_type = 1,
		id = 9015,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9016] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]1个可升级词条",
		goods_num = 1,
		resource_type = 1,
		id = 9016,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9017] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]1个可升级词条",
		goods_num = 1,
		resource_type = 1,
		id = 9017,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9018] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]1个升级次数",
		goods_num = 1,
		resource_type = 1,
		id = 9018,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9019] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]2个升级次数",
		goods_num = 1,
		resource_type = 1,
		id = 9019,
		icon = "benefit_2_xingchengou_3",
		goods_id_list = {
			3200103
		}
	},
	[9020] = {
		goods_type = 3,
		name = "1个刷新次数（塔罗牌）",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 6,
		desc = "[测试配置，无需本地化]1个刷新次数（塔罗牌）-by benefit",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9020,
		icon = "benefit_2_xingchengou_3"
	},
	[9021] = {
		goods_type = 3,
		name = "2个刷新次数（塔罗牌）",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 6,
		desc = "[测试配置，无需本地化]2个刷新次数（塔罗牌）-by benefit",
		goods_id_list = "",
		goods_num = 2,
		resource_type = 1,
		id = 9021,
		icon = "benefit_2_xingchengou_3"
	},
	[9022] = {
		goods_type = 3,
		name = "1个刷新次数（商店）",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 5,
		desc = "[测试配置，无需本地化]1个刷新次数（商店）-by benefit",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9022,
		icon = "benefit_2_xingchengou_3"
	},
	[9023] = {
		goods_type = 3,
		name = "2个刷新次数（商店）",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 5,
		desc = "[测试配置，无需本地化]2个刷新次数（商店）-by benefit",
		goods_id_list = "",
		goods_num = 2,
		resource_type = 1,
		id = 9023,
		icon = "benefit_2_xingchengou_3"
	},
	[9024] = {
		goods_type = 4,
		name = "Temperance Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个节制释义",
		goods_num = 1,
		resource_type = 1,
		id = 9024,
		icon = "buff_2008",
		goods_id_list = {
			3830008
		}
	},
	[9025] = {
		goods_type = 4,
		name = "The Sun Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个太阳释义",
		goods_num = 1,
		resource_type = 1,
		id = 9025,
		icon = "buff_2008",
		goods_id_list = {
			3830009
		}
	},
	[9026] = {
		goods_type = 4,
		name = "The Star Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个星星释义",
		goods_num = 1,
		resource_type = 1,
		id = 9026,
		icon = "buff_2008",
		goods_id_list = {
			3830010
		}
	},
	[9027] = {
		goods_type = 4,
		name = "The Tower Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个高塔释义",
		goods_num = 1,
		resource_type = 1,
		id = 9027,
		icon = "buff_2008",
		goods_id_list = {
			3830011
		}
	},
	[9028] = {
		goods_type = 4,
		name = "The Devil Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个恶魔释义",
		goods_num = 1,
		resource_type = 1,
		id = 9028,
		icon = "buff_2008",
		goods_id_list = {
			3830012
		}
	},
	[9029] = {
		goods_type = 4,
		name = "The Empress Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个女皇释义",
		goods_num = 1,
		resource_type = 1,
		id = 9029,
		icon = "buff_2008",
		goods_id_list = {
			3830013
		}
	},
	[9030] = {
		goods_type = 4,
		name = "The Hanged Man Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个倒吊者释义",
		goods_num = 1,
		resource_type = 1,
		id = 9030,
		icon = "buff_2008",
		goods_id_list = {
			3830014
		}
	},
	[9031] = {
		goods_type = 4,
		name = "The World Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个世界释义",
		goods_num = 1,
		resource_type = 1,
		id = 9031,
		icon = "buff_2008",
		goods_id_list = {
			3830015
		}
	},
	[9032] = {
		goods_type = 4,
		name = "The Moon Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个月亮释义",
		goods_num = 1,
		resource_type = 1,
		id = 9032,
		icon = "buff_2008",
		goods_id_list = {
			3830016
		}
	},
	[9033] = {
		goods_type = 4,
		name = "The Chariot Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个战车释义",
		goods_num = 1,
		resource_type = 1,
		id = 9033,
		icon = "buff_2008",
		goods_id_list = {
			3830017
		}
	},
	[9034] = {
		goods_type = 4,
		name = "Judgment Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个审判释义",
		goods_num = 1,
		resource_type = 1,
		id = 9034,
		icon = "buff_2008",
		goods_id_list = {
			3830018
		}
	},
	[9035] = {
		goods_type = 4,
		name = "Justice Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个正义释义",
		goods_num = 1,
		resource_type = 1,
		id = 9035,
		icon = "buff_2008",
		goods_id_list = {
			3830019
		}
	},
	[9036] = {
		goods_type = 4,
		name = "The High Priestess Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个女祭司释义",
		goods_num = 1,
		resource_type = 1,
		id = 9036,
		icon = "buff_2008",
		goods_id_list = {
			3830020
		}
	},
	[9037] = {
		goods_type = 4,
		name = "Wheel of Fortune Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个命运之轮释义",
		goods_num = 1,
		resource_type = 1,
		id = 9037,
		icon = "buff_2008",
		goods_id_list = {
			3830021
		}
	},
	[9038] = {
		goods_type = 4,
		name = "Strength Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个力量释义",
		goods_num = 1,
		resource_type = 1,
		id = 9038,
		icon = "buff_2008",
		goods_id_list = {
			3830022
		}
	},
	[9039] = {
		goods_type = 4,
		name = "The Magician Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个魔术师释义",
		goods_num = 1,
		resource_type = 1,
		id = 9039,
		icon = "buff_2008",
		goods_id_list = {
			3830023
		}
	},
	[9040] = {
		goods_type = 4,
		name = "The Hierophant Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个教皇释义",
		goods_num = 1,
		resource_type = 1,
		id = 9040,
		icon = "buff_2008",
		goods_id_list = {
			3830024
		}
	},
	[9041] = {
		goods_type = 4,
		name = "The Fool Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个愚者释义",
		goods_num = 1,
		resource_type = 1,
		id = 9041,
		icon = "buff_2008",
		goods_id_list = {
			3830025
		}
	},
	[9042] = {
		goods_type = 4,
		name = "Death Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个死神释义",
		goods_num = 1,
		resource_type = 1,
		id = 9042,
		icon = "buff_2008",
		goods_id_list = {
			3830026
		}
	},
	[9043] = {
		goods_type = 4,
		name = "The Emperor Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个皇帝释义",
		goods_num = 1,
		resource_type = 1,
		id = 9043,
		icon = "buff_2008",
		goods_id_list = {
			3830027
		}
	},
	[9044] = {
		goods_type = 4,
		name = "The Hermit Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个隐者释义",
		goods_num = 1,
		resource_type = 1,
		id = 9044,
		icon = "buff_2008",
		goods_id_list = {
			3830028
		}
	},
	[9045] = {
		goods_type = 4,
		name = "The Lovers Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个恋人释义",
		goods_num = 1,
		resource_type = 1,
		id = 9045,
		icon = "buff_2008",
		goods_id_list = {
			3830029
		}
	},
	[9046] = {
		goods_type = 4,
		name = "Swords Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个宝剑释义",
		goods_num = 1,
		resource_type = 1,
		id = 9046,
		icon = "buff_2008",
		goods_id_list = {
			3830030
		}
	},
	[9047] = {
		goods_type = 4,
		name = "Wands Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个权杖释义",
		goods_num = 1,
		resource_type = 1,
		id = 9047,
		icon = "buff_2008",
		goods_id_list = {
			3830031
		}
	},
	[9048] = {
		goods_type = 4,
		name = "Cups Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个圣杯释义",
		goods_num = 1,
		resource_type = 1,
		id = 9048,
		icon = "buff_2008",
		goods_id_list = {
			3830032
		}
	},
	[9049] = {
		goods_type = 4,
		name = "Pentacles Reading",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个星币释义",
		goods_num = 1,
		resource_type = 1,
		id = 9049,
		icon = "buff_2008",
		goods_id_list = {
			3830033
		}
	},
	[9050] = {
		goods_type = 4,
		name = "Random Tarot Card",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 0,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_num = 1,
		resource_type = 1,
		id = 9050,
		icon = "buff_2008",
		goods_id_list = {
			3200103
		}
	},
	[9051] = {
		goods_type = 1,
		name = "塔罗牌 · 愚者",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810701,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9051,
		icon = "buff_2008"
	},
	[9052] = {
		goods_type = 1,
		name = "塔罗牌 · 魔术师",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810621,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9052,
		icon = "buff_2008"
	},
	[9053] = {
		goods_type = 1,
		name = "塔罗牌 · 女祭司",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810781,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9053,
		icon = "buff_2008"
	},
	[9054] = {
		goods_type = 1,
		name = "塔罗牌 · 女皇",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810321,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9054,
		icon = "buff_2008"
	},
	[9055] = {
		goods_type = 1,
		name = "塔罗牌 · 皇帝",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3811041,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9055,
		icon = "buff_2008"
	},
	[9056] = {
		goods_type = 1,
		name = "塔罗牌 · 教皇",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810661,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9056,
		icon = "buff_2008"
	},
	[9057] = {
		goods_type = 1,
		name = "塔罗牌 · 恋人",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810821,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9057,
		icon = "buff_2008"
	},
	[9058] = {
		goods_type = 1,
		name = "塔罗牌 · 战车",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810921,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9058,
		icon = "buff_2008"
	},
	[9059] = {
		goods_type = 1,
		name = "塔罗牌 · 力量",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810581,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9059,
		icon = "buff_2008"
	},
	[9060] = {
		goods_type = 1,
		name = "塔罗牌 · 隐者",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810741,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9060,
		icon = "buff_2008"
	},
	[9061] = {
		goods_type = 1,
		name = "塔罗牌 · 命运之轮",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810541,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9061,
		icon = "buff_2008"
	},
	[9062] = {
		goods_type = 1,
		name = "塔罗牌 · 正义",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810441,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9062,
		icon = "buff_2008"
	},
	[9063] = {
		goods_type = 1,
		name = "塔罗牌 · 倒吊者",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810381,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9063,
		icon = "buff_2008"
	},
	[9064] = {
		goods_type = 1,
		name = "塔罗牌 · 死神",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3811081,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9064,
		icon = "buff_2008"
	},
	[9065] = {
		goods_type = 1,
		name = "塔罗牌 · 节制",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810011,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9065,
		icon = "buff_2008"
	},
	[9066] = {
		goods_type = 1,
		name = "塔罗牌 · 恶魔",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810261,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9066,
		icon = "buff_2008"
	},
	[9067] = {
		goods_type = 1,
		name = "塔罗牌 · 高塔",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810191,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9067,
		icon = "buff_2008"
	},
	[9068] = {
		goods_type = 1,
		name = "塔罗牌 · 星星",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810131,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9068,
		icon = "buff_2008"
	},
	[9069] = {
		goods_type = 1,
		name = "塔罗牌 · 月亮",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810861,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9069,
		icon = "buff_2008"
	},
	[9070] = {
		goods_type = 1,
		name = "塔罗牌 · 太阳",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810071,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9070,
		icon = "buff_2008"
	},
	[9071] = {
		goods_type = 1,
		name = "塔罗牌 · 审判",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810981,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9071,
		icon = "buff_2008"
	},
	[9072] = {
		goods_type = 1,
		name = "塔罗牌 · 世界",
		resource_num = 1,
		is_refresh = 1,
		limit_num = 99,
		goods_id = 3810481,
		desc = "[测试配置，无需本地化]选择并获得1个塔罗牌",
		goods_id_list = "",
		goods_num = 1,
		resource_type = 1,
		id = 9072,
		icon = "buff_2008"
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		42,
		43,
		44,
		45,
		46,
		47,
		48,
		49,
		50,
		51,
		52,
		53,
		54,
		55,
		56,
		57,
		58,
		59,
		60,
		61,
		62,
		63,
		3001,
		3002,
		3003,
		3004,
		3005,
		3006,
		3007,
		3008,
		3009,
		3010,
		3011,
		3012,
		3013,
		3014,
		3015,
		3016,
		3017,
		3018,
		3019,
		3020,
		3101,
		3102,
		3103,
		3104,
		3105,
		3106,
		3107,
		3108,
		3109,
		3110,
		3111,
		3112,
		3116,
		3120,
		3124,
		3128,
		3132,
		3136,
		3140,
		3144,
		3148,
		3152,
		3156,
		3160,
		3164,
		3168,
		3172,
		3176,
		3180,
		3184,
		3188,
		3192,
		3196,
		3200,
		3204,
		3208,
		3212,
		3216,
		3220,
		3224,
		3228,
		3232,
		3236,
		3240,
		3244,
		3248,
		3252,
		3256,
		3260,
		3264,
		3268,
		3272,
		3276,
		3280,
		3284,
		3288,
		3292,
		3296,
		3300,
		3304,
		3308,
		3312,
		3316,
		3320,
		9001,
		9002,
		9003,
		9004,
		9005,
		9006,
		9007,
		9008,
		9009,
		9010,
		9011,
		9012,
		9013,
		9014,
		9015,
		9016,
		9017,
		9018,
		9019,
		9020,
		9021,
		9022,
		9023,
		9024,
		9025,
		9026,
		9027,
		9028,
		9029,
		9030,
		9031,
		9032,
		9033,
		9034,
		9035,
		9036,
		9037,
		9038,
		9039,
		9040,
		9041,
		9042,
		9043,
		9044,
		9045,
		9046,
		9047,
		9048,
		9049,
		9050,
		9051,
		9052,
		9053,
		9054,
		9055,
		9056,
		9057,
		9058,
		9059,
		9060,
		9061,
		9062,
		9063,
		9064,
		9065,
		9066,
		9067,
		9068,
		9069,
		9070,
		9071,
		9072
	}
}
