pg = pg or {}
pg.child2_shop = {
	{
		goods_type = 1,
		name = "Fitness +10 (Fixed Amount)",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2022,
		desc = "Fitness +10 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 1,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +10 (Fixed Amount)",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2023,
		desc = "Knowledge +10 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 2,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +10 (Fixed Amount)",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2024,
		desc = "Dexterity +10 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 3,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +10 (Fixed Amount)",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2025,
		desc = "Sensitivity +10 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 4,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +2 (Fixed Amount)",
		resource_num = 8,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2026,
		desc = "Mood +2 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 5,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness +20 (Fixed Amount)",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2027,
		desc = "Fitness +20 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 6,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +20 (Fixed Amount)",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2028,
		desc = "Knowledge +20 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 7,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +20 (Fixed Amount)",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2029,
		desc = "Dexterity +20 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 8,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +20 (Fixed Amount)",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2030,
		desc = "Sensitivity +20 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 9,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +4 (Fixed Amount)",
		resource_num = 12,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2031,
		desc = "Mood +4 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 10,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness +40 (Fixed Amount)",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2032,
		desc = "Fitness +40 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 11,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "Knowledge +40 (Fixed Amount)",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2033,
		desc = "Knowledge +40 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 12,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "Dexterity +40 (Fixed Amount)",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2034,
		desc = "Dexterity +40 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 13,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "Sensitivity +40 (Fixed Amount)",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2035,
		desc = "Sensitivity +40 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 14,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "Mood +6 (Fixed Amount)",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2036,
		desc = "Mood +6 (Fixed Amount)",
		goods_num = 1,
		resource_type = 1,
		id = 15,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "Fitness Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2001,
		desc = "Activity Fitness Boost (3 Turns)",
		goods_num = 1,
		resource_type = 1,
		id = 16,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "Knowledge Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2002,
		desc = "Activity Knowledge Boost (3 Turns)",
		goods_num = 1,
		resource_type = 1,
		id = 17,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "Dexterity Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2003,
		desc = "Activity Dexterity Boost (3 Turns)",
		goods_num = 1,
		resource_type = 1,
		id = 18,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "Sensitivity Boost",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2004,
		desc = "Activity Sensitivity Boost (3 Turns)",
		goods_num = 1,
		resource_type = 1,
		id = 19,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "Lucky Coupon",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2005,
		desc = "Grants between 20 and 100 Funds when obtained.",
		goods_num = 1,
		resource_type = 1,
		id = 20,
		icon = "buff_2005"
	},
	{
		goods_type = 1,
		name = "Random Fitness Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2006,
		desc = "For 3 turns, when you complete an activity, you gain a little Fitness.",
		goods_num = 1,
		resource_type = 1,
		id = 21,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "Random Knowledge Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2007,
		desc = "For 3 turns, when you complete an activity, you gain a little Knowledge.",
		goods_num = 1,
		resource_type = 1,
		id = 22,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "Random Dexterity Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2008,
		desc = "For 3 turns, when you complete an activity, you gain a little Dexterity.",
		goods_num = 1,
		resource_type = 1,
		id = 23,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "Random Sensitivity Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2009,
		desc = "For 3 turns, when you complete an activity, you gain a little Sensitivity.",
		goods_num = 1,
		resource_type = 1,
		id = 24,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "Random Fitness Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2010,
		desc = "For 3 turns, when you complete an activity, you gain some Fitness.",
		goods_num = 1,
		resource_type = 1,
		id = 25,
		icon = "benefit_2_tineng_2"
	},
	{
		goods_type = 1,
		name = "Random Knowledge Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2011,
		desc = "For 3 turns, when you complete an activity, you gain some Knowledge.",
		goods_num = 1,
		resource_type = 1,
		id = 26,
		icon = "benefit_2_zhishi_2"
	},
	{
		goods_type = 1,
		name = "Random Dexterity Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2012,
		desc = "For 3 turns, when you complete an activity, you gain some Dexterity.",
		goods_num = 1,
		resource_type = 1,
		id = 27,
		icon = "benefit_2_shijian_2"
	},
	{
		goods_type = 1,
		name = "Random Sensitivity Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2013,
		desc = "For 3 turns, when you complete an activity, you gain some Sensitivity.",
		goods_num = 1,
		resource_type = 1,
		id = 28,
		icon = "benefit_2_ganzhi_2"
	},
	{
		goods_type = 1,
		name = "Delayed Random Fitness Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2014,
		desc = "When the next turn ends, you gain a lot of Fitness.",
		goods_num = 1,
		resource_type = 1,
		id = 29,
		icon = "benefit_2_tineng_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Knowledge Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2015,
		desc = "When the next turn ends, you gain a lot of Knowledge.",
		goods_num = 1,
		resource_type = 1,
		id = 30,
		icon = "benefit_2_zhishi_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Dexterity Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2016,
		desc = "When the next turn ends, you gain a lot of Dexterity.",
		goods_num = 1,
		resource_type = 1,
		id = 31,
		icon = "benefit_2_shijian_3"
	},
	{
		goods_type = 1,
		name = "Delayed Random Sensitivity Boost",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2017,
		desc = "When the next turn ends, you gain a lot of Sensitivity.",
		goods_num = 1,
		resource_type = 1,
		id = 32,
		icon = "benefit_2_ganzhi_3"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery",
		resource_num = 25,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2018,
		desc = "For 3 turns, when the turn starts, you recover a little Mood.",
		goods_num = 1,
		resource_type = 1,
		id = 33,
		icon = "benefit_2_xinqing_1"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery+",
		resource_num = 36,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2019,
		desc = "For 3 turns, when the turn starts, you recover some Mood.",
		goods_num = 1,
		resource_type = 1,
		id = 34,
		icon = "benefit_2_xinqing_2"
	},
	{
		goods_type = 1,
		name = "Random Mood Recovery++",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2020,
		desc = "For 3 turns, when the turn starts, you recover a lot of Mood.",
		goods_num = 1,
		resource_type = 1,
		id = 35,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 1,
		name = "Permanent Random Mood Recovery",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2021,
		desc = "When the turn starts, you recover some Mood.",
		goods_num = 1,
		resource_type = 1,
		id = 36,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 3,
		name = "Action Point Recovery",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "Purchase to recover 1 action point.",
		goods_num = 1,
		resource_type = 1,
		id = 37,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 3,
		name = "Action Point Recovery+",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "Purchase to recover 2 action points.",
		goods_num = 2,
		resource_type = 1,
		id = 38,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 1,
		name = "Fitness Conversion - Knowledge",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2037,
		desc = "For 3 turns, activities give more Fitness and less Knowledge.",
		goods_num = 1,
		resource_type = 1,
		id = 39,
		icon = "benefit_2_tinengzhishiz"
	},
	{
		goods_type = 1,
		name = "Knowledge Conversion - Fitness",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2038,
		desc = "For 3 turns, activities give more Knowledge and less Fitness.",
		goods_num = 1,
		resource_type = 1,
		id = 40,
		icon = "benefit_2_zhishitinengz"
	},
	{
		goods_type = 1,
		name = "Dexterity Conversion - Sensitivity",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2039,
		desc = "For 3 turns, activities give more Dexterity and less Sensitivity.",
		goods_num = 1,
		resource_type = 1,
		id = 41,
		icon = "benefit_2_shijianganzhiz"
	},
	{
		goods_type = 1,
		name = "Sensitivity Conversion - Dexterity",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2040,
		desc = "For 3 turns, activities give more Sensitivity and less Dexterity.",
		goods_num = 1,
		resource_type = 1,
		id = 42,
		icon = "benefit_2_ganzhishijianz"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2041,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 43,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2043,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 44,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Dexterity Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2045,
		desc = "(Alternating) More Dexterity gained/less Dexterity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 45,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2047,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_num = 1,
		resource_type = 1,
		id = 46,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2049,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_num = 1,
		resource_type = 1,
		id = 47,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Fitness Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2051,
		desc = "(Alternating) More Fitness gained/less Fitness gained.",
		goods_num = 1,
		resource_type = 1,
		id = 48,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2053,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 49,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2055,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 50,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Sensitivity Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2057,
		desc = "(Alternating) More Sensitivity gained/less Sensitivity gained.",
		goods_num = 1,
		resource_type = 1,
		id = 51,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2059,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_num = 1,
		resource_type = 1,
		id = 52,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2061,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_num = 1,
		resource_type = 1,
		id = 53,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Alternating Knowledge Boost++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2063,
		desc = "(Alternating) More Knowledge gained/less Knowledge gained.",
		goods_num = 1,
		resource_type = 1,
		id = 54,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2089,
		desc = "Slightly increases stats gained from the 1st activity slot.",
		goods_num = 1,
		resource_type = 1,
		id = 55,
		icon = "benefit_2_xingcheng1_1"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2090,
		desc = "Moderately increases stats gained from the 1st activity slot.",
		goods_num = 1,
		resource_type = 1,
		id = 56,
		icon = "benefit_2_xingcheng1_2"
	},
	{
		goods_type = 1,
		name = "Special Activity Slot - First++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2091,
		desc = "Greatly increases stats gained from the 1st activity slot.",
		goods_num = 1,
		resource_type = 1,
		id = 57,
		icon = "benefit_2_xingcheng1_3"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2092,
		desc = "Slightly increases stats gained from odd-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 58,
		icon = "benefit_2_xingchengji_1"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2093,
		desc = "Moderately increases stats gained from odd-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 59,
		icon = "benefit_2_xingchengji_2"
	},
	{
		goods_type = 1,
		name = "Odd-Numbered Activity Slot Boost++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2094,
		desc = "Greatly increases stats gained from odd-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 60,
		icon = "benefit_2_xingchengji_3"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2095,
		desc = "Slightly increases stats gained from even-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 61,
		icon = "benefit_2_xingchengou_1"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2096,
		desc = "Moderately increases stats gained from even-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 62,
		icon = "benefit_2_xingchengou_2"
	},
	{
		goods_type = 1,
		name = "Even-Numbered Activity Slot Boost++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2097,
		desc = "Greatly increases stats gained from even-numbered activity slots.",
		goods_num = 1,
		resource_type = 1,
		id = 63,
		icon = "benefit_2_xingchengou_3"
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		42,
		43,
		44,
		45,
		46,
		47,
		48,
		49,
		50,
		51,
		52,
		53,
		54,
		55,
		56,
		57,
		58,
		59,
		60,
		61,
		62,
		63
	}
}
