pg = pg or {}
pg.enemy_data_statistics_398 = {
	[296241] = {
		cannon = 323,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		pilot_ai_template_id = 70270,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		speed = 20,
		reload = 150,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		id = 296241,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		scale = 100,
		hit_growth = 0,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 0.7
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201050,
				LV = 1
			}
		}
	},
	[296242] = {
		cannon = 342,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		pilot_ai_template_id = 70270,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		speed = 20,
		reload = 150,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		id = 296242,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		scale = 100,
		hit_growth = 0,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 0.7
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201050,
				LV = 1
			}
		}
	},
	[296243] = {
		cannon = 361,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		pilot_ai_template_id = 70270,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		speed = 20,
		reload = 150,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		id = 296243,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		scale = 100,
		hit_growth = 0,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 0.7
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201050,
				LV = 1
			}
		}
	},
	[296244] = {
		cannon = 380,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		pilot_ai_template_id = 70270,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		speed = 20,
		reload = 150,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		id = 296244,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		scale = 100,
		hit_growth = 0,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 0.7
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201050,
				LV = 1
			}
		}
	},
	[296245] = {
		cannon = 400,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		pilot_ai_template_id = 70270,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		speed = 20,
		reload = 150,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		id = 296245,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		scale = 100,
		hit_growth = 0,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 0.7
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201050,
				LV = 1
			}
		}
	},
	[296246] = {
		cannon = 133,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296246,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296247] = {
		cannon = 152,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296247,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296248] = {
		cannon = 171,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296248,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296249] = {
		cannon = 190,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296249,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296250] = {
		cannon = 209,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296250,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296251] = {
		cannon = 228,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296251,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296252] = {
		cannon = 247,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296252,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296253] = {
		cannon = 266,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296253,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296254] = {
		cannon = 285,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296254,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296255] = {
		cannon = 304,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296255,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296256] = {
		cannon = 323,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296256,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296257] = {
		cannon = 342,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296257,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296258] = {
		cannon = 361,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296258,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296259] = {
		cannon = 380,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296259,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296260] = {
		cannon = 400,
		fog_fx = "",
		rarity = 2,
		speed_growth = 0,
		speed = 20,
		air = 0,
		luck = 0,
		dodge = 0,
		cannon_growth = 0,
		reload = 150,
		id = 296260,
		reload_growth = 0,
		dodge_growth = 0,
		icon = "sairenboss11",
		star = 2,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		torpedo = 0,
		base = 90535,
		durability = 99999,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		antiaircraft_growth = 0,
		armor = 0,
		durability_growth = 0,
		antiaircraft = 0,
		antisub = 0,
		hit_growth = 0,
		scale = 100,
		cld_box = {
			0.1,
			0.1,
			0.1
		},
		specific_fx_scale = {
			jiejie_loop = 1.2
		},
		appear_fx = {
			"jiejie_loop"
		},
		buff_list = {
			{
				ID = 201057,
				LV = 1
			}
		}
	},
	[296261] = {
		cannon = 135,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296261,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 9333,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296262] = {
		cannon = 155,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296262,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 10666,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296263] = {
		cannon = 174,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296263,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 12000,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296264] = {
		cannon = 193,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296264,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 13333,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296265] = {
		cannon = 213,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296265,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 14666,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296266] = {
		cannon = 232,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296266,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 16000,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296267] = {
		cannon = 251,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296267,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 17333,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296268] = {
		cannon = 271,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296268,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 18666,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296269] = {
		cannon = 290,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296269,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 20000,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296270] = {
		cannon = 310,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296270,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 21333,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	},
	[296271] = {
		cannon = 329,
		battle_unit_type = 15,
		fog_fx = "",
		speed_growth = 0,
		pilot_ai_template_id = 20006,
		air = 0,
		speed = 25,
		dodge = 0,
		id = 296271,
		cannon_growth = 0,
		rarity = 1,
		reload_growth = 0,
		dodge_growth = 0,
		armor = 0,
		star = 1,
		hit = 0,
		antisub_growth = 0,
		air_growth = 0,
		reload = 150,
		base = 90977,
		durability = 22666,
		armor_growth = 0,
		torpedo_growth = 0,
		luck_growth = 0,
		hit_growth = 0,
		luck = 0,
		torpedo = 0,
		durability_growth = 0,
		antisub = 0,
		antiaircraft = 0,
		antiaircraft_growth = 0,
		equipment_list = {},
		buff_list = {}
	}
}
