_G.pg.base.item_virtual_data_statistics[40126] = {
	album_config = "",
	display = "This item will instantly raise your Commander Level to 70 upon purchase. Does nothing if your Commander Level is already at or above 70.",
	drop_arg = "",
	drop_gold_max = 0,
	drop_oil_max = 0,
	icon = "Props/lv_70",
	id = 40126,
	is_world = 0,
	link_id = 0,
	max_num = 0,
	name = "Instant Commander Level 70",
	order = 0,
	rarity = 4,
	replace_item = 0,
	shop_id = -1,
	time_limit = 0,
	type = 0,
	virtual_type = 23,
	display_icon = {},
	price = {},
	index = {},
	shiptrans_id = {},
	combination_display = {},
}

