_G.pg.base.ship_skin_words[100000] = {
	battle = "I don't know what I'm doing, but I'm doing it, buli!",
	detail = "Buli? Buli? Where are we? What are we gonna do here?",
	drop_descrip = "Universal Bulin. Can be used to limit break all ships of Elite rarity or below.",
	expedition = "Buli! The girls are back!",
	feeling1 = "Wahh~! Commander is a big, big dummy!",
	feeling2 = "My big sis can apparently only strengthen one color. I can strengthen a bunch! Which means... that I'm more powerful than her? Wow! I'm stronger than her, buli!",
	feeling3 = "Bulin is happy that she can help everyone get stronger, but she enjoys playing with you too, Commander! Bulin can help strengthen you... Aww, why not?",
	feeling4 = "I'm not meant for combat, yet you use me anyway, so being the more sensible Bulin, I need to thank you! I guess it's just because we're too cute...? *Kyah~* I might be in love~!",
	feeling5 = "My heart races whenever I see you, Commander! I could dismantle the entire dock for you! Could this be... my inner fire? Buli!",
	gift_dislike = "",
	gift_prefer = "",
	headtouch = "",
	home = "Buli! Look, I'm full of energy!",
	hp_warning = "",
	id = 100000,
	login = "If I swing this wrench hard enough, I could poke a hole in the office floor, buli!",
	lose = "Huh? Am I... no good in battle, buli?",
	mail = "Something strange just popped outta me, buli...",
	main = "Us Bulins are pretty awesome, buli!|Is there nothing for Bulin to do? Really? Then let's go play! Wheee!|Commander, let's go dig for some treasure, buli~!",
	mission = "Buli? What's the mission?",
	mission_complete = "Rewards... Can I eat them, buli?",
	profile = "They say I'm just like my sister, but we're actually in charge of different colors... What's a color? Sounds yummy!",
	propose = "Bulin has been caught~ Ahh, I'm blushing so much! What will I do! Let's buy some new toys and celebrate!",
	skill = "My wrench is the wrench that will pierce the earth!",
	touch = "Buli? Do you want to be bulified?",
	touch2 = "Buli? ... ... Buli?",
	unlock = "Buli? Seems like I can help make your fleet stronger, buli!",
	upgrade = "[Cannot be enhanced]",
	voice_key = 10000,
	voice_key_2 = -1,
	vote = "",
	win_mvp = "Buli? Could it be that... I'm super strong?!",
	couple_encourage = {
		{
			{
				10001,
			},
			1,
			"Sis, what are you bulin here?",
			0,
		},
	},
}

