_G.pg.base.weapon_property_2[183751] = {
	action_index = "",
	aim_type = 1,
	angle = 16,
	attack_attribute = 1,
	attack_attribute_ratio = 100,
	auto_aftercast = 0,
	axis_angle = 16,
	charge_param = "",
	corrected = 100,
	damage = 27,
	effect_move = 0,
	expose = 0,
	fire_fx = "",
	fire_fx_loop_type = 1,
	fire_sfx = "",
	id = 183751,
	initial_over_heat = 0,
	min_range = 0,
	queue = 1,
	range = 500,
	recover_time = 0,
	reload_max = 9500,
	search_type = 2,
	shakescreen = 0,
	spawn_bound = "cannon",
	suppress = 1,
	torpedo_ammo = 0,
	type = 2,
	bullet_ID = {
		171000,
	},
	barrage_ID = {
		81140,
	},
	oxy_type = {
		1,
	},
	search_condition = {
		1,
	},
	precast_param = {},
}

