_G.pg.base.weapon_property_1[2] = {
	action_index = "attack",
	aim_type = 1,
	angle = 360,
	attack_attribute = 1,
	attack_attribute_ratio = 100,
	auto_aftercast = 0.5,
	axis_angle = 0,
	charge_param = "",
	corrected = 110,
	damage = 45,
	effect_move = 0,
	expose = 0,
	fire_fx = "zhupao",
	fire_fx_loop_type = 1,
	fire_sfx = "battle/cannon-356mm",
	id = 2,
	initial_over_heat = 0,
	min_range = 0,
	queue = 1,
	range = 80,
	recover_time = 0.5,
	reload_max = 240,
	search_type = 1,
	shakescreen = 0,
	spawn_bound = "cannon",
	suppress = 1,
	torpedo_ammo = 0,
	type = 2,
	bullet_ID = {
		1400,
	},
	barrage_ID = {
		8,
	},
	oxy_type = {
		1,
	},
	search_condition = {
		1,
	},
	precast_param = {},
}

