_G.pg.base.weapon_property_2[5680] = {
	action_index = "attack",
	aim_type = 1,
	angle = 80,
	attack_attribute = 2,
	attack_attribute_ratio = 100,
	auto_aftercast = 0,
	axis_angle = 0,
	charge_param = "",
	corrected = 100,
	damage = 82,
	effect_move = 0,
	expose = 0,
	fire_fx = "",
	fire_fx_loop_type = 1,
	fire_sfx = "",
	id = 5680,
	initial_over_heat = 1,
	min_range = 0,
	queue = 1,
	range = 37,
	recover_time = 0.5,
	reload_max = 4060,
	search_type = 1,
	shakescreen = 0,
	spawn_bound = "torpedo",
	suppress = 1,
	torpedo_ammo = 0,
	type = 16,
	bullet_ID = {
		1845,
	},
	barrage_ID = {
		1402,
	},
	oxy_type = {
		1,
	},
	search_condition = {
		1,
	},
	precast_param = {},
}

