_G.pg.base.weapon_property_2[171021] = {
	action_index = "attack",
	aim_type = 0,
	angle = 120,
	attack_attribute = 2,
	attack_attribute_ratio = 100,
	auto_aftercast = 0,
	axis_angle = 0,
	charge_param = "",
	corrected = 100,
	damage = 18,
	effect_move = 0,
	expose = 0,
	fire_fx = "",
	fire_fx_loop_type = 1,
	fire_sfx = "",
	id = 171021,
	initial_over_heat = 0,
	min_range = 0,
	queue = 1,
	range = 80,
	recover_time = 0.5,
	reload_max = 400,
	search_type = 1,
	shakescreen = 0,
	spawn_bound = "torpedo",
	suppress = 0,
	torpedo_ammo = 0,
	type = 3,
	bullet_ID = {
		171021,
	},
	barrage_ID = {
		171021,
	},
	oxy_type = {
		1,
	},
	search_condition = {
		1,
	},
	precast_param = {},
}

