local var0_0 = class("NewEducateConst")

var0_0.NEW_EDUCATE_SELECT_ID = "NEW_EDUCATE_SELECT_ID"
var0_0.NEW_EDUCATE_SKIP_PLANS_ANIM = "NEW_EDUCATE_SKIP_PLANS_ANIM"
var0_0.NEW_EDUCATE_EVENT_TIP = "NEW_EDUCATE_EVENT_TIP"
var0_0.NEW_EDUCATE_NEW_CHILD_TIP = "NEW_EDUCATE_NEW_CHILD_TIP"
var0_0.DROP_TYPE = {
	ATTR = 1,
	RES = 2,
	POLAROID = 3,
	BUFF = 4
}
var0_0.CONDITION_TYPE = {
	NORMAL_SITE_CNT = 5,
	DROP = 1,
	ROUND = 4,
	ATTR_SUM = 2,
	EVENT_SITE_CNT = 3
}
var0_0.PERFORM_TYPE = {
	WORD = 4,
	MINIGAME = 3,
	STORY = 5,
	PICTURE = 7,
	OPTION = 2,
	BUBBLE = 6,
	CPK = 1
}
var0_0.WORD_TYPE = {
	HIDE_IMAGE = 6,
	PLAYER = 2,
	SITE_RIGHT = 5,
	CHILD = 1,
	SITE_LEFT = 4,
	ASIDE = 3,
	SITE_ASIDE = 0
}
var0_0.SITE_TYPE = {
	SHOP = 2,
	WORK = 3,
	EVENT = 5,
	SHIP = 1,
	TRAVEL = 4
}
var0_0.SITE_NORMAL_TYPE = {
	WORK = 1,
	TRAVEL = 2
}
var0_0.SITE_STATE_TYPE = {
	SHIP = 3,
	NORMAL = 2,
	EVENT = 1
}
var0_0.EFFECT_TYPE = {
	REDUCE_GOODS_CSOT = 23,
	EXTRA_PLAN = 7,
	REDUCE_PLAN_COST = 22
}
var0_0.TYPEWRITE_SPEED = 0.05
var0_0.TYPEWRITE_SPEED_UP = 0.01
var0_0.LOCK_ENDING = false
var0_0.LOCK_GUIDE = false

return var0_0
