local var0 = class("PrayPoolConst")

var0.SWITCH_TO_HOME_PAGE = "SWITCH_TO_HOME_PAGE"
var0.SWITCH_TO_SELECT_POOL_PAGE = "SWITCH_TO_SELECT_POOL_PAGE"
var0.SWITCH_TO_SELECT_SHIP_PAGE = "SWITCH_TO_SELECT_SHIP_PAGE"
var0.CLICK_INDEX_BTN = "CLICK_INDEX_BTN"
var0.CLICK_BUILD_BTN = "CLICK_BUILD_BTN"
var0.START_BUILD_SHIP_EVENT = "START_BUILD_SHIP_EVENT"
var0.BUILD_PRAY_POOL_CMD = "BUILD_PRAY_POOL_CMD"
var0.BUILD_PRAY_POOL_SUCCESS = "BUILD_PRAY_POOL_SUCCESS"

return var0
