local var0_0 = class("EducateBaseUI", import("view.base.BaseUI"))

var0_0.EDUCATE_GO_SCENE = "EDUCATE_GO_SCENE"
var0_0.EDUCATE_CHANGE_SCENE = "EDUCATE_CHANGE_SCENE"
var0_0.EDUCATE_GO_SUBLAYER = "EDUCATE_GO_SUBLAYER"
var0_0.EDUCATE_ON_AWARD = "EDUCATE_ON_AWARD"
var0_0.EDUCATE_ON_ITEM = "EDUCATE_ON_ITEM"
var0_0.EDUCATE_ON_MSG_TIP = "EDUCATE_ON_MSG_TIP"
var0_0.EDUCATE_ON_UNLOCK_TIP = "EDUCATE_ON_UNLOCK_TIP"

function var0_0.getGroupName(arg0_1)
	return LayerWeightConst.GROUP_EDUCATE
end

return var0_0
