local var0 = class("CourtYardConst")

var0.SYSTEM_DEFAULT = 1
var0.SYSTEM_VISIT = 2
var0.SYSTEM_FEAST = 3
var0.SYSTEM_OUTSIDE = 4
var0.SYSTEM_EDIT_FEAST = 5
var0.STYLE_INNER = 1
var0.STYLE_OUTSIDE = 2
var0.STYLE_FEAST = 3
var0.STYLE_PREVIEW = 4
var0.DEPTH_TYPE_MAT = 0
var0.DEPTH_TYPE_SHIP = 1
var0.DEPTH_TYPE_FURNITURE = 2
var0.BELONG_FLOOR = 1
var0.BELONG_WALL = 2
var0.MAX_STOREY_LEVEL = 3
var0.OPEN_AREA_PRE_LEVEL = 4
var0.BACKYARD_RED = Color.New(1, 0.294, 0.08)
var0.BACKYARD_GREEN = Color.New(0.48, 1, 0.03)
var0.BACKYARD_BLUE = Color.New(0.3, 0.63, 0.95)
var0.OBJ_TYPE_SHIP = 1
var0.OBJ_TYPE_COMMOM = 2
var0.OBJ_TYPE_SPINE = 3
var0.SHIP_SCALE = 0.5
var0.SHIP_TYPE_SELF = 1
var0.SHIP_TYPE_OTHER = 2
var0.SHIP_TYPE_FEAST = 3
var0.FEAST_EFFECT_TIME = 3
var0.FEAST_CHAT_TIME = 15
var0.FEAST_GIVE_TICKET_ANIM_TIME = 8
var0.FEAST_GIVE_GIFT_ANIM_TIME = 2

return var0
