local var0 = class("Fushun3GameEvent")

var0.game_over_call = "game over call"
var0.catch_item_call = "catch item call"
var0.create_item_call = "create item call"
var0.create_platform_item_call = "create platform item call"
var0.item_follow_call = "item follow call"
var0.create_monster_call = "create monster call"
var0.player_attack_call = "player_attack_call"
var0.check_player_damage = "check monster damage"
var0.check_item_damage = "check item damage"
var0.char_damaged_call = "char damaged call"
var0.add_anim_effect_call = "add effect call"
var0.add_effect_call = "add effect call"
var0.power_speed_call = "power speed call"
var0.add_monster_score_call = "add monster score call"
var0.power_damage_monster_call = "power_damage_monster"
var0.shot_damage_monster_call = "shot damage monster"
var0.attack_damdage_monster_call = "attack damage monster"
var0.kick_damage_monster_call = "kick damage monster"
var0.script_jump_event = "fushun3 jump event "
var0.script_attack_event = "fushun3 attake event"
var0.script_power_event = "fushun3 power event"
var0.day_night_change = "day night change"

return var0
